<?php

foreach ($this->settings->catalogSettings as $value) {
	if (!strpos('subscription', $value))
		${$value} = $this->settings->getCatalogSetting($this->rowId, $value, 'category');
}

extract(\Mobbex\Repository::getPlansFilterFields($this->rowId, $common_plans, $advanced_plans));

include 'plans-filter.phtml';
if($this->settings->get('multivendor'))
	include 'multivendor.phtml';

$this->helper->executeHook('mobbexCategorySettings', false, $this->rowId);
