<?php

// Get transaction information
    $order = $this->getOrder();
    $trx   = Mage::getModel('mobbex/transaction')->getMobbexTransaction(['order_id' => $order->getRealOrderId(), 'parent' => 1]);

    if (empty($trx['total']))
        return;
?>

<script>    
    
    var financingCost = <?= $trx['total'] - $order->getGrandTotal() ?>;
    var newTotal = <?= $trx['total'] ?>;
    // Find a <table> element by class
    var tableTotal = document.getElementsByClassName("order-totals")[0].getElementsByTagName("tfoot");

    //only if there is a financing cost added, the total is change
    if(financingCost > 0){
        const trTotal = document.createElement('tr');
        trTotal.innerHTML = '<tr class="0"><td class="label"><strong>Grand Total Paid</strong></td><td class="emph"><strong><span class="price">$'+newTotal+'</span></strong></td></tr>';
        tableTotal[0].insertBefore(trTotal,tableTotal[0].firstChild);//add new total
    }
    const tr = document.createElement('tr');
    //add financing total cost
    tr.innerHTML = '<td class="label">Financing Cost</td><td ><span class="price">$'+financingCost+' </span> </td>'
    tableTotal[0].insertBefore(tr,tableTotal[0].firstChild);

</script>