<?php
    $mobbexData = $this->mobbexTransaction->getMobbexTransaction(['order_id' => $this->getInfo()->getOrder()->getIncrementId(), 'parent' => 1]);
    $cards      = $this->filterCards($mobbexData && $mobbexData['operation_type'] == 'payment.multiple-sources' ? $this->mobbexTransaction->getMobbexTransaction(['order_id' => $this->getInfo()->getOrder()->getIncrementId()]) : false);
    $coupon     = isset($mobbexData['entity_uid']) && isset($mobbexData['payment_id']) ? "https://mobbex.com/console/" . $mobbexData['entity_uid'] . "/operations/?oid=" . $mobbexData['payment_id'] : '';
?>

<table>
<tr>
    <th>Mobbex Payment Information</th>
</tr>
<tr>
    <td>Transaction ID:</td>
    <td><?= isset($mobbexData['payment_id']) ? $mobbexData['payment_id'] : '' ?></td>
</tr>
<tr>
    <td>Total:</td>
    <td><?= isset($mobbexData['total']) ? $mobbexData['total'] : '' ?></td>
</tr>
<tr>
    <th>Payment Sources</th>
</tr>
<tr>
    <td>Payment Method:</td>
    <td><?= isset($mobbexData['source_type']) ? $mobbexData['source_type'] : '' ?></td>
</tr>

<?php if($cards) : ?>
    <?php foreach($cards as $key => $card): ?>
        <?php if($card['source_name'] !== "multicard"): ?>
            <tr>
                <th><?= 'Card '.($key + 1)  ?></th>
            </tr>
            <tr>
                <td>Name:</td>
                <td><?= isset($card['source_name']) ? $card['source_name'] : '' ?></td>
            </tr>
            <tr>
                <td>Number:</td>
                <td><?= isset($card['source_number']) ? $card['source_number'] : '' ?></td>
            </tr>
            <tr>
                <td>Installment:</td>
                <td><?= isset($card['source_installment']) ? json_decode($card['source_installment'], true)['description'] . ' ' . json_decode($card['source_installment'], true)['count'] . ' cuota/s' : '' ?></td>
            </tr>
            <tr>
                <td>Amount:</td>
                <td><?= isset($card['total']) ? $card['total'] : '' ?></td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
<?php else : ?>
    <tr>
        <td>Source name:</td>
        <td><?= isset($mobbexData['source_name']) ? $mobbexData['source_name'] : '' ?></td>
    </tr>
    <tr>
        <td>Source Info:</td>
        <td><?= isset($mobbexData['source_number']) ? $mobbexData['source_number'] : '' ?></td>
    </tr>
    <tr>
        <td>Source Installment:</td>
        <td><?= isset($mobbexData['source_installment']) ? json_decode($mobbexData['source_installment'], true)['description'] . ' ' . json_decode($mobbexData['source_installment'], true)['count'] . ' cuota/s' : '' ?></td>
    </tr>
<?php endif; ?>

<tr>
    <th>Entity Data</th>
</tr>
<tr>
    <td>Risk Analysis:</td>
    <td><?= isset($mobbexData['risk_analysis']) ? $mobbexData['risk_analysis'] : '' ?></td>
</tr>
<tr>
    <td>Coupon:</td>
    <td><a href="<?= $coupon ?>">View</a></td>
</tr>
</table>