<?php
$mobbexData = $this->mobbexTransaction->getMobbexTransaction(['order_id' => $this->getInfo()->getOrder()->getIncrementId(), 'parent' => 1]);
$cards      = !empty($mobbexData['childs']) ? $this->mobbexTransaction->getMobbexChilds(json_decode($mobbexData['childs'], true), $mobbexData['order_id']) : false;
$entities   = !empty($mobbexData['childs']) ? $this->mobbexTransaction->getMobbexChilds(json_decode($mobbexData['childs'], true), $mobbexData['order_id']) : false;
$coupon     = "https://mobbex.com/console/" . $mobbexData['entity_uid'] . "/operations/?oid=" . $mobbexData['payment_id'];
?>

<table>
    <tr>
        <th>Mobbex Payment Information</th>
    </tr>
    <tr>
        <td>Transaction ID:</td>
        <td><?= isset($mobbexData['payment_id']) ? $mobbexData['payment_id'] : '' ?></td>
    </tr>
    <tr>
        <td>Total:</td>
        <td><?= isset($mobbexData['total']) ? $mobbexData['total'] : '' ?></td>
    </tr>
    <tr>
        <th>Payment Sources</th>
    </tr>
    <tr>
        <td>Payment Method:</td>
        <td><?= isset($mobbexData['source_name']) ? $mobbexData['source_name'] : '' ?></td>
    </tr>

    <?php if ($mobbexData['operation_type'] == 'payment.multiple-sources' && $cards) : ?>
        <?php foreach ($cards as $key => $card) : ?>
            <tr>
                <th><?= 'Card ' . ($key + 1)  ?></th>
            </tr>
            <tr>
                <td>Name:</td>
                <td><?= isset($card['source_name']) ? $card['source_name'] : '' ?></td>
            </tr>
            <tr>
                <td>Number:</td>
                <td><?= isset($card['source_number']) ? $card['source_number'] : '' ?></td>
            </tr>
            <tr>
                <td>Installment:</td>
                <td><?= isset($card['source_installment']) ? json_decode($card['source_installment'], true)['description'] . ' ' . json_decode($card['source_installment'], true)['count'] . ' cuota/s' : '' ?></td>
            </tr>
            <tr>
                <td>Amount:</td>
                <td><?= isset($card['total']) ? $card['total'] : '' ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else : ?>
        <tr>
            <td>Source name:</td>
            <td><?= isset($mobbexData['source_type']) ? $mobbexData['source_type'] : '' ?></td>
        </tr>
        <tr>
            <td>Source Info:</td>
            <td><?= isset($mobbexData['source_number']) ? $mobbexData['source_number'] : '' ?></td>
        </tr>
        <tr>
            <td>Source Installment:</td>
            <td><?= isset($mobbexData['source_installment']) ? json_decode($mobbexData['source_installment'], true)['description'] . ' ' . json_decode($mobbexData['source_installment'], true)['count'] . ' cuota/s' : '' ?></td>
        </tr>
    <?php endif; ?>

    <tr>
        <th>Entity Data</th>
    </tr>
    <?php if ($mobbexData['operation_type'] == 'payment.multiple-vendor' && $entities) : ?>
        <?php foreach ($entities as $key => $entity) : ?>
            <tr>
                <th><?= 'Entity ' . ($key + 1)  ?></th>
            </tr>
            <tr>
                <td>Name:</td>
                <td><?= isset($entity['entity_name']) ? $entity['entity_name'] : '' ?></td>
            </tr>
            <tr>
                <td>UID:</td>
                <td><?= isset($entity['entity_uid']) ? $entity['entity_uid'] : '' ?></td>
            </tr>
        <?php endforeach; ?>
    <?php else : ?>
        <tr>
            <td>Name:</td>
            <td><?= isset($mobbexData['entity_name']) ? $mobbexData['entity_name'] : '' ?></td>
        </tr>
        <tr>
            <td>UID:</td>
            <td><?= isset($mobbexData['entity_uid']) ? $mobbexData['entity_uid'] : '' ?></td>
        </tr>
    <?php endif; ?>
    <tr>
        <td>Risk Analysis:</td>
        <td><?= isset($mobbexData['risk_analysis']) ? $mobbexData['risk_analysis'] : '' ?></td>
    </tr>
    <tr>
        <td>Coupon:</td>
        <td><a href="<?= $coupon ?>">View</a></td>
    </tr>
</table>