
<div class="multivendor entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit.form fieldset-legend"><?= $this->__('Entity Configuration') ?></h4>
    </div>
    <div class="fieldset fieldset-wide" id="mobbex_options">
        <div class="hor-scroll">
            <h3><?= $this->__('Multivendor') ?></h3>
	    	<label style="margin-top: 20px;" for="entity"><?= $this->__('Entity UID:') ?></label>
            <input type="text" id="entity" name="entity" value="<?= $entity ?>">
	    </div>
    </div>
</div>