<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?= $this->__('Plans Configuration') ?></h4>
	</div>
	<div class="fieldset fieldset-wide" id="mobbex_options">
		<div class="hor-scroll">
			<h3><?= $this->__('Select the plans you want to appear in the checkout') ?></h3>
			<div class="mbbx_plans_cont">
				<div class="mbbx_plan_list">
					<p><?= $this->__('Common plans') ?></p>
					<?php foreach ($this->commonPlans as $planId => $data) : ?>
						<div>
							<input type="hidden" name="<?= $planId ?>" value="no">
							<input type='checkbox' name='<?= $planId ?>' id='<?= $planId ?>' <?= ($data['value'] ? 'checked' : '') ?>>
							<label for='<?= $planId ?>'><?= $data['label'] ?></label>
						</div>
					<?php endforeach; ?>
				</div>
				<div class="mbbx_plan_list">
					<p><?= $this->__('Plans with advanced rules') ?></p>
					<?php foreach ($this->advancedPlans as $sourceRef => $sourceData) : ?>
						<div class='mbbx_plan_source'>
							<img src='https://res.mobbex.com/images/sources/<?= $sourceRef ?>.png'><?= key($sourceData) ?>
						</div>
						<?php foreach (reset($sourceData) as $planId => $data) : ?>
							<div>
								<input type='checkbox' name='<?= $planId ?>' id='<?= $planId ?>' <?= ($data['value'] ? 'checked' : '') ?>>
								<label for='<?= $planId ?>'><?= $data['label'] ?></label>
							</div>
						<?php endforeach; ?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>

	<div class="mbbx-subscription">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit.form fieldset-legend"><?= $this->__('Subscriptions') ?></h4>
		</div>
		<div class="fieldset fieldset-wide" id="mobbex_options">
			<div class="hor-scroll">
				<h3><?= $this->__('Check if the product is a subscription') ?></h3>
				<label style="margin-top: 20px;" for="sub_enable"><?= $this->__('Subscription:') ?></label>
				<select id="sub_enable" name="sub_enable"  onchange="document.querySelector('#subscription_uid').classList.toggle('mbbx-hidden')">
					<option value="no" <?= $this->subscription['enable'] === 'no' ? 'selected' : '' ?>>No</option>
					<option value="yes" <?= $this->subscription['enable'] === 'yes' ? 'selected' : '' ?>>Yes</option>
				</select>
				<div class="<?= $this->subscription['enable'] === 'no' ? 'mbbx-hidden' : '' ?>" id="subscription_uid" style="margin-top: 20px;">
					<label style="margin-right: 10px;" for="sub_uid"><?= $this->__('Subscription UID:') ?></label>
					<input type="text" name="sub_uid" id="sub_uid" value="<?= $this->subscription['uid'] ?>" >
				</div>
			</div>
		</div>
	</div>

	<style>
		.mbbx-hidden {
			display: none;
		}
	</style>

</div>