<?php

// Get plans with current values
$plans = $this->getPlans();
$plans_html = '';

// Section tittle
$tittle = __('Elija los planes que NO quiera que aparezcan durante la compra');

foreach ($plans as $plan => $data) {
	$enabled = ($data['value'] === 'yes');
	$plans_html .=
		"<tr>
			<td class='value'>
				<input type='checkbox' name='".$plan."' id='".$plan."' " . ($enabled ? 'checked' : '') . ">
			</td>
			<td class='label' style='width: 100%;'><label for='" . $plan . "'>" . $data['label'] . "</label></td>
		</tr>";
}
?>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend">Mobbex Options</h4>
	</div>
	<div class="fieldset fieldset-wide" id="mobbex_options">
		<div class="hor-scroll">
			<table cellspacing="0" class="form-list">
				<tbody>
					<h3><?= $tittle ?></h3>
					<?= $plans_html ?>
				</tbody>
			</table>
		</div>
	</div>
</div>