<?php
// If embed is disabled
if(!Mage::getStoreConfig('payment/mobbex/embed')) {
	return;
}

$order_url = Mage::getUrl('mobbex/payment/getCheckout', array('_secure' => true));
$script_url = $this->getSkinUrl('js/mobbex_embed.js');
?>
<form name="mobbexform" method="get"></form>
<div id="mbbx-container"></div>

<script type="text/javascript">
	var orderUrl = '<?= $order_url ?>';
</script>
<script type="text/javascript" src="https://res.mobbex.com/js/embed/mobbex.embed@1.0.17.js"></script>
<script type="text/javascript" src="<?= $script_url ?>"></script>