<?php if($this->enable): ?>
<div id="mbbxProductModal" class="mobbex-plans-modal <?= $this->styles['theme'] ?>">
        <div id="mbbxProductModalContent" class="">
            <div id="mbbxProductModalHeader">
                <label id="mobbex_select_title" for="mbbx-method-select">Seleccione un método de pago</label>
                <span id="closembbxProduct">&times;</span>
                <select name="mbbx-method-select" id="mbbx-method-select">
                    <option id="0" value="0">Todos</option>
                    <?php foreach ($this->sources as $source) : ?>
                        <?php if (!empty($source['source']['name'])) : ?>
                            <option id="{$source['source']['reference']}" value="<?= $source['source']['reference'] ?>">
                                <?= $source['source']['name'] ?>
                            </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div id="mbbxProductModalBody">
                <?php foreach ($this->sources as $source) : ?>
                    <?php if (!empty($source['source']['name'])) : ?>
                        <div id="<?= $source['source']['reference'] ?>" class="mobbexSource">
                            <p class="mobbexPaymentMethod">
                                <img src="https://res.mobbex.com/images/sources/<?= $source['source']['reference'] ?>.jpg"><?= $source['source']['name'] ?>
                            </p>
                            <?php if (!empty($source['installments']['list'])) : ?>
                                <table class="installmentsTable">
                                    <?php foreach ($source['installments']['list'] as $installment) : ?>
                                        <tr>
                                            <td <?=$this->action !== 'catalog_product_view'? 'style="padding-left:40px;font-weight:bold;text-align:left;margin-left:40px;"': ''?>><?= $installment['name'] ?></td>
                                            <?php if (isset($installment['totals']['total'])) : ?>
                                                <td <?=$this->action !== 'catalog_product_view' ? 'style="padding-right:40px;font-size:12px;font-weight:bold;"' : ''?> class="mbbxPlansPrice"><?= $installment['totals']['total'] ?></td>
                                            <?php else : ?>
                                                <td></td>
                                            <?php endif; ?>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <button type="button" id="mbbxProductBtn" onclick="toggleFinancialWidget(event)">
        <?php if($this->styles['logo']): ?>
        <img src="<?= $this->styles['logo'] ?>" alt="" width="40" height="40" style="margin-right: 10px; border-radius: 40px;">
        <?php endif; ?>
        <?= $this->styles['text'] ?>
    </button>

    
    <style>
        
        /* Custom styles */
        <?= $this->styles['css'] ?>
        
        /* CLOSE-OPEN BUTTONS */
        #mbbxProductBtn {
            display: flex;
            align-items: center;
        }
        #closembbxProduct {
            font-size: 35px;
            color: rgb(0, 0, 0);
            cursor: pointer;
            margin-bottom: 10px;
        }
        
        .dark #closembbxProduct {
            color: white;
        }
        
        #closembbxProduct:hover {
            
            cursor: pointer;
        }
        
        .scroll-lock {
            padding-right: 17px;
            overflow: hidden;
        }
        
        /* MODAL STYLES */
        
        /* The Modal (background) */
        #mbbxProductModal {
            display: none;
            /* Hidden by default */
            position: fixed;
            /* Stay in place */
            left: 0;
            top: 0;
            width: 100%;
            /* Full width */
            height: 100%;
            /* Full height */
            overflow: auto;
            /* Enable scroll if needed */
            background-color: rgb(0, 0, 0);
            /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4);
            /* Black w/ opacity */
            z-index: 9999;
            place-items: center;
        }

        #mbbxProductModal.active {
            display: grid;
        }

        /* Modal Content/Box */
        #mbbxProductModalContent {
            background-color: #fefefe;
            padding: 20px;
            border: 1px solid #888;
            max-width: 650px;
            /* Could be more or less, depending on screen size */
            height: 90%;
            /* Full height */
            width: 100%;
            z-index: 10000;
            overflow-y: scroll;
            border-radius: 10px;
        }

        #mbbxProductModalHeader {
            display: flex;
            justify-content: space-between;
            flex-flow: wrap;
            align-items: center;
        }
        
        /* Modal Scrollbar */
        #mbbxProductModalContent::-webkit-scrollbar {
            width: 20px;
        }

        #mbbxProductModalContent::-webkit-scrollbar-track {
            background-color: transparent;
        }

        #mbbxProductModalContent::-webkit-scrollbar-thumb {
            background-color: #d6dee1;
            border-radius: 20px;
            border: 6px solid transparent;
            background-clip: content-box;
        }

        #mbbxProductModalContent::-webkit-scrollbar-thumb:hover {
            background-color: #a8bbbf;
        }

        .mobbexPaymentMethod {
            display: flex;
            align-items: center;
            padding: 1em 0;
            margin: 0;
            font-weight: bold;
        }
        
        #mbbxProductModalBody td {
            width: 65%;
        }

        .mobbexPaymentMethod img {
            height: 40px;
            border-radius: 100%;
            margin-right: 10px;
        }
        
        #mbbx-method-select {
            width: 100%;
            min-height: 40px;
            padding: 0.5rem;
            border: 1px #d8d8d8 solid;
            border-radius: 5px;
        }

        .installmentsTable {
            margin-bottom: 20px;
            width: 80%;
            margin: 0 auto;
        }
        
        .installmentsTable tr {
            width: 100%;
            padding: 10px;
            padding-left: 20px;
        }

        .installmentsTable td {
            padding: 10px 0;
            width: 70%;
        }
        
        .mbbxPlansPrice {
            text-align: end;
        }
        
        /* DARK MODE  */
        .dark #mbbxProductModalContent,
        .dark #mbbxProductModalContent table td {
            background-color: rgb(39, 31, 36);
            color: rgb(226, 226, 226);
        }

        .dark #mbbxProductModalContent #mobbex_select_title,
        .dark #mbbxProductModalContent .mobbexPaymentMethod {
            color: rgb(226, 226, 226);
        }
        </style>

<script>
        document.addEventListener('DOMContentLoaded', () => {
            
            // Get modal action buttons
            var openBtn = document.getElementById('mbbxProductBtn');
            var closeBtn = document.querySelector('#closembbxProduct');
            var mobbexPlansModal = document.querySelector('#mbbxProductModal');
            
            // Add events to toggle modal
            mobbexPlansModal.addEventListener('click', function(e) {
                if (e.target === closeBtn || e.target === mobbexPlansModal) {
                    toggleFinancialWidget(e);
                }
                return false;
            });

            // Get sources and payment method selector 
            var sources = document.querySelectorAll('.mobbexSource');
            var methodSelect = document.getElementById('mbbx-method-select');
            
            // Filter payment methods in the modal
            methodSelect.addEventListener('change', function() {
                for (source of sources)
                    source.style.display = source.id != methodSelect.value && methodSelect.value != 0 ? 'none' : '';
                });
        });
        
        function toggleFinancialWidget(e) {
            e.target.preventDefault;
            document.querySelector('#mbbxProductModal').classList.toggle('active')
            document.querySelector('body').classList.toggle('scroll-lock');
        }

        </script>
        <?php endif; ?>