<?php
// Get primary color config
$color = (new Mobbex_Mobbex_Helper_Settings)->get('color');

foreach ($this->data['methods'] as $method) :
?>
    <dt id="dt_method_mobbex_<?= $method['id'] ?>" style="display:flex;align-items: center;">
    <input id="p_method_mobbex_<?= $method['id'] ?>" value="<?= $method['value'] ?>" 
        type="radio" 
        name="form_key"
        class="radio mbbx-payment-method-input"
        style="float: none;top:-4px;"
        />
    <label for="p_method_mobbex_<?= $method['id']?>" style="display:flex;align-items:center;margin-left:12px;padding-left:33px;">
        <?php if($method['image']): ?>
            <div class="method-img-cont">
                <img src="<?= $method['image'] ?>">
            </div>
        <?php endif; ?>
        <?= $method['name']?>
    </label>

    </dt>
    <?php
endforeach;

foreach ($this->data['cards'] as $card) :
    if (!empty($card['installments'])) :
    ?>
        <dt id="dt_method_mobbex_<?= $card['id'] ?>">
            <div class="card" style="display:flex;align-items: center;">
                <input id="p_method_mobbex_<?= $card['id'] ?>" value="<?= $card['value'] ?>" type="radio" name="form_key" class="radio mbbx-payment-method-input mbbx-card" style="float: none;top:-4px;" />
                <label for="p_method_mobbex_<?= $card['id'] ?>" style="display:flex;align-items:center;margin-left:12px;padding-left:33px;">
                    <?php if ($card['image']) : ?>
                        <div class="method-img-cont">
                            <img src="<?= $card['image'] ?>">
                        </div>
                    <?php endif; ?>
                    <?= $card['name'] ?>
                </label>
            </div>
            <div class="mobbex-wallet-form mbbx-hidden" id="<?= $card['value'] ?>" style="margin-left: 25px;">
                <select name="installment" style="height:30px; max-width: 200px; padding: 0 9px;">
                    <?php foreach ($card['installments'] as $installment) : ?>
                        <div class="mbbx-card-installments">
                            <option value="<?= $installment['reference'] ?>"><?= $installment['name'] ?></option>
                        </div>
                    <?php endforeach; ?>
                </select>
                <input style="margin: 20px 0; max-width: 100px;" type="password" maxlenght="<?= $card['maxlenght'] ?>" placeholder="<?= $card['placeholder'] ?>" name="security-code" required>
                <input type="hidden" name="card-number" value="<?= $card['hiddenValue'] ?>">
            </div>
        </dt>
<?php
    endif;
endforeach;
?>

<style>
    .mbbx-hidden {
        display: none;
    }

    img[src*='res.mobbex'],
    img[src*='res.sugaway'] {
        max-height: 35px;
        border-radius: 100%;
    }

    .method-img-cont {
        background-color: #6f00ff;
        margin-right: 5px;
        border-radius: 100%;
        width: 30px;
        height: 30px;
        display: flex;
        place-items: center;
        justify-content: center;
    }
</style>
<script>
    document.querySelector('#dt_method_mobbex').setAttribute('style', 'display:none;');
</script>