<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order = $_order->loadByIncrementId($orderId);

// Get Redirect URL
$redirect_url = Mage::helper('mobbex/data')->createCheckout($order);
?>
<form name="mobbexform" method="get" action="<?php echo $redirect_url; ?>"></form>
<script type="text/javascript">
	document.mobbexform.submit();
</script>